AWSTemplateFormatVersion: 2010-09-09
Description: SecurityLayer
 
# Metadata:

Parameters:
  #SystemName
  SystemName:
    Type: String
    Default: Sample


# Mappings: 
# Conditions:
# Transform:

Resources:
  #******************************************
  #
  #セキュリティグループ作成
  #
  #******************************************
  #ALB用セキュリティグループ
  AlbScg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${SystemName}-alb-scg"
      GroupDescription: Allow SSH and HTTP access only MyIP
      VpcId: !ImportValue VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${SystemName}-alb-scg"


Outputs:
  AlbScg:
    Value: !Ref AlbScg
    Export: 
      Name: AlbScg

